Created a new EarthquakeApplication class that will be used for insta…
Kvaibhav01/Quake-Report pull request #15
Opened 2018-10-09 18:33 UTC by alistairholmes

Created a new Application class for the Instabug reporting. Also added the required dependency :)

2018-10-10 13:49 UTC, Kvaibhav01 requested changes
Unfortunately, you have not registered the `EarthquakeApplication` in the Manifest. Nothing happenes when I take a screenshot or shake the phone.

2018-10-10 14:11 UTC, alistairholmes commented
Oh snap! My bad, totally forgot to commit the manifest file.

2018-10-10 14:36 UTC, Kvaibhav01 requested changes
There is this error in earthquake_activity.xml:

_Android resource compilation failed
Output:  Quake-Info-master\app\src\main\res\layout\earthquake_activity.xml:26: error: mismatched tag._

There are some issues with the ordering/opening-closing of tags. Check that.

2018-10-11 07:57 UTC, Kvaibhav01 commented on app/src/main/java/com/theQuake/quakeInfo/EarthquakeActivity.java
> +                loaderManager.initLoader(EARTHQUAKE_LOADER_ID, null, EarthquakeActivity.this);
It says wrong third argument type. It requires `LoaderCallbacks` in `EarthquakeActivity.this`.

2018-10-11 08:00 UTC, Kvaibhav01 requested changes
Your swipe layout had some error in the EarthquakeActivity.java file at line 86:

`swipe = findViewById(R.id.swiperefresh);` There was no id with `swiperefresh`. 

I tested with the screenshot, InstaBug works perfectly! Kudos 🎉. But still, the shake feature doesn't work 😞. Try it with your phone and let me know. Also, check the comment I made on line 130 of EarthquakeActivity file.

2019-04-18 06:55 UTC, Kvaibhav01 commented
@alistairholmes are you working on this or should I close this PR?

2019-04-18 06:56 UTC, Kvaibhav01 commented
Closing this PR as no active contribution/activity was noted.

2019-04-18 06:56 UTC, closed without merging